<?php

class FaultCodeType {
	static $paramtypesmap = array(
	);
	const ACCT_TEMP_UNAVAILABLE = "ACCT_TEMP_UNAVAILABLE";
	const EMAIL_ADDRS_REQD = "EMAIL_ADDRS_REQD";
	const INVALID_ACCT = "INVALID_ACCT";
	const INVALID_JOB_ID = "INVALID_JOB_ID";
	const INVALID_LOGIN_CREDENTIALS = "INVALID_LOGIN_CREDENTIALS";
	const INVALID_PAGE_INDEX = "INVALID_PAGE_INDEX";
	const INVALID_ROLE = "INVALID_ROLE";
	const INVALID_WS_VERSION = "INVALID_WS_VERSION";
	const JOB_NOT_COMPLETE = "JOB_NOT_COMPLETE";
	const LOGIN_DISABLED = "LOGIN_DISABLED";
	const MAX_RCRDS_EXCEEDED = "MAX_RCRDS_EXCEEDED";
	const OI_FEATURE_REQD = "OI_FEATURE_REQD";
	const OI_PERMISSION_REQD = "OI_PERMISSION_REQD";
	const PSWD_REQD = "PSWD_REQD";
	const ROLE_REQUIRED = "ROLE_REQUIRED";
	const SESSION_TIMED_OUT = "SESSION_TIMED_OUT";
	const UNEXPECTED_ERROR = "UNEXPECTED_ERROR";
	const UNSUPPORTED_WS_VERSION = "UNSUPPORTED_WS_VERSION";
	const USER_ERROR = "USER_ERROR";
	const WS_CONCUR_SESSION_DISALLWD = "WS_CONCUR_SESSION_DISALLWD";
	const WS_FEATURE_REQD = "WS_FEATURE_REQD";
	const WS_PERMISSION_REQD = "WS_PERMISSION_REQD";
	const WS_LOG_IN_REQD = "WS_LOG_IN_REQD";
}

